name: Terraform Metastore Plan and Apply
on:
  workflow_dispatch

env:
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  AZDO_ORG_SERVICE_URL: ${{secrets.AZDO_ORG_SERVICE_URL}}
  AZDO_PERSONAL_ACCESS_TOKEN: ${{secrets.AZDO_PERSONAL_ACCESS_TOKEN}}
  azure_client_secret: ${{secrets.TF_VAR_AZURE_CLIENT_SECRET}}
  databricks_account_id: ${{secrets.TF_VAR_DATABRICKS_ACCOUNT_ID}}
  databricks_sp_terraform: ${{secrets.TF_VAR_DATABRICKS_SP_TERRAFORM}}
  databricks_user_email: ${{secrets.TF_VAR_DATABRICKS_USER_EMAIL}}
  sql_server_user: ${{secrets.TF_VAR_SQL_SERVER_USER}}
  sql_server_password: ${{secrets.TF_VAR_SQL_SERVER_PASSWORD}}
  vm_user: ${{secrets.TF_VAR_VM_USER}}
  vm_password: ${{secrets.TF_VAR_VM_PASSWORD}}
  prefix_name: ${{secrets.TF_VAR_PREFIX_NAME}}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: cd metastore && terraform init

      - name: Terraform Plan
        run: |
          cd metastore
          terraform validate
          terraform plan \
            -var="azure_client_secret=${{secrets.TF_VAR_AZURE_CLIENT_SECRET}}" \
            -var="databricks_account_id=${{secrets.TF_VAR_DATABRICKS_ACCOUNT_ID}}" \
            -var="databricks_sp_terraform=${{ secrets.TF_VAR_DATABRICKS_SP_TERRAFORM }}" \
            -var="databricks_user_email=${{ secrets.TF_VAR_DATABRICKS_USER_EMAIL }}" \
            -var="sql_server_user=${{secrets.TF_VAR_SQL_SERVER_USER}}" \
            -var="sql_server_password=${{secrets.TF_VAR_SQL_SERVER_PASSWORD}}" \
            -var="vm_user=${{secrets.TF_VAR_VM_USER}}" \
            -var="vm_password=${{secrets.TF_VAR_VM_PASSWORD}}" \
            -var="prefix_name=${{secrets.TF_VAR_PREFIX_NAME}}" 

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: cd metastore && terraform init

      - name: Terraform Apply
        run: |
          cd metastore
          terraform validate
          terraform apply -auto-approve \
            -var="azure_client_secret=${{secrets.TF_VAR_AZURE_CLIENT_SECRET}}" \
            -var="databricks_account_id=${{secrets.TF_VAR_DATABRICKS_ACCOUNT_ID}}" \
            -var="databricks_sp_terraform=${{ secrets.TF_VAR_DATABRICKS_SP_TERRAFORM }}" \
            -var="databricks_user_email=${{ secrets.TF_VAR_DATABRICKS_USER_EMAIL }}" \
            -var="sql_server_user=${{secrets.TF_VAR_SQL_SERVER_USER}}" \
            -var="sql_server_password=${{secrets.TF_VAR_SQL_SERVER_PASSWORD}}" \
            -var="vm_user=${{secrets.TF_VAR_VM_USER}}" \
            -var="vm_password=${{secrets.TF_VAR_VM_PASSWORD}}" \
            -var="prefix_name=${{secrets.TF_VAR_PREFIX_NAME}}" 